image:
  file: .gitpod.Dockerfile

ports:
  - port: 26657
    onOpen: ignore
  - port: 1317
    onOpen: ignore

tasks:
  - name: Setup Environment
    init: |
      # Install Rust
      curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
      source $HOME/.cargo/env
      
      # Install required cargo tools
      cargo install cargo-generate --features vendored-openssl
      cargo install cargo-run-script
      
      # Install Go
      wget https://golang.org/dl/go1.22.5.linux-amd64.tar.gz
      sudo tar -C /usr/local -xzf go1.22.5.linux-amd64.tar.gz
      echo 'export PATH=$PATH:/usr/local/go/bin' >> ~/.bashrc
      
      # Setup environment variables
      echo 'export NODE="--node https://rpc.testnet.mantrachain.io:443"' >> ~/.bashrc
      echo 'export CHAIN_ID="mantrachain-testnet-1"' >> ~/.bashrc
      echo 'export TXFLAG="${NODE} --chain-id ${CHAIN_ID} --gas-prices 0.025uaum --gas auto --gas-adjustment 1.3"' >> ~/.bashrc
      
      # Clone example repository
      gh repo fork https://github.com/0xmetaschool/building-on-MANTRA-chain.git --clone
      
    command: |
      source ~/.bashrc
      echo "Environment setup complete! 🚀"

vscode:
  extensions:
    - rust-lang.rust-analyzer
    - serayuzgur.crates
    - golang.go
    - github.copilot
    - github.vscode-pull-request-github
